# Generated by Django 5.0 on 2024-02-23 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_invitation_place_invitation_time_invitation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='recipients_groups',
            field=models.ManyToManyField(related_name='recipients_groups', to='socialnetwork.group'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='recipients_users',
            field=models.ManyToManyField(related_name='recipients_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
