# Generated by Django 5.0 on 2024-02-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0009_alter_invitation_recipients_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='socialnetwork.question')),
            ],
        ),
    ]
